version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: django-mysql-crud-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"  # Puertos expuestos (3307 en el host, 3306 en el contenedor)
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-mysql-crud-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: django-mysql-crud-phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - backend

  adminer:
    image: adminer
    container_name: django-mysql-crud-adminer
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
